---
- name: Create VM from Proxmox Template
  hosts: proxmox
  vars:
    ansible_python_interpreter: /opt/venv/bin/python
  tasks:
    - name: Install necessary packages via apt
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-setuptools
          - python3-venv
        state: present
      become: yes

    - name: Create virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv /opt/venv
      args:
        creates: /opt/venv

    - name: Install requests module in virtual environment
      ansible.builtin.command:
        cmd: /opt/venv/bin/pip install requests

    - name: Install proxmoxer module in virtual environment
      ansible.builtin.command:
        cmd: /opt/venv/bin/pip install proxmoxer

    - name: Clone Proxmox template
      community.general.proxmox_kvm:
        node: pve-in
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"
        api_host: 172.18.0.251
        api_port: 8006
        storage: "local-lvm"
        full: true
        clone: "centOStemplate"
        name: "{{ vm_name }}"

    - name: Wait for VM to boot
      ansible.builtin.wait_for:
        host: "{{ new_IP }}"
        port: 22
        timeout: 300

    - name: Start VM
      community.general.proxmox_kvm:
        node: proxmox
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"
        api_host: 172.18.0.251
        api_port: 8006
        name: "{{ vm_name }}"
        state: started

- name: Set VM IP and Hostname
  hosts: "{{ new_IP }}"
  tasks:
    - name: Update IP
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-vmbr1
        regex: "^IPADDR="
        line: "IPADDR={{ new_IP }}"
        backup: yes

    - name: Update Hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}.cvd.local"

    - name: Reboot VM
      ansible.builtin.reboot:
        reboot_timeout: 300
      become: yes

    - name: Wait for VM to become available
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: 300
