- name: Manage Virtual Machines in Proxmox
  hosts: 172.28.0.251
  vars:
    proxmox_host: "172.28.0.251"
    proxmox_user: "root@pam"
    proxmox_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
    proxmox_node: "pve-in"
    vm_name: "new-vm"  # Имя новой виртуальной машины
    cores: 2           # Количество процессоров
    memory: 2048       # Размер памяти в МБ
    disk_size: "20G"   # Размер виртуального диска
    storage: "local-lvm"  # Хранилище, где будет размещён диск
    iso_path: "local:iso/ubuntu-22.04.4-live-server-amd64.iso"  # Путь к ISO-образу
    bridge: "vmbr1"    # Сетевой мост для VM
    ansible_python_interpreter: /usr/bin/python3.11

  tasks:
    - name: Get the next available VMID
      command: pvesh get /cluster/nextid
      register: next_vmid
      become: true
      changed_when: false

    - name: Create a new virtual machine
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ next_vmid.stdout }}"
        name: "{{ vm_name }}"
        cores: "{{ cores }}"
        memory: "{{ memory }}"
        net: "model=virtio,bridge={{ bridge }}"
        scsihw: "virtio-scsi-pci"
        boot: "order=scsi0;net0"
        onboot: true
        state: present

    - name: Attach ISO to the VM
      command: >
        qm set {{ next_vmid.stdout }}
        --ide2 {{ iso_path }},media=cdrom
      become: true

    - name: Add a virtual disk
      command: >
        qm set {{ next_vmid.stdout }}
        --scsi0 {{ storage }}:{{ disk_size }}
      become: true

    - name: Start the virtual machine
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ next_vmid.stdout }}"
        state: started

    - name: Output VM details
      debug:
        msg: "VM '{{ vm_name }}' with VMID '{{ next_vmid.stdout }}' created and started successfully on Proxmox node '{{ proxmox_node }}'."
