---
- name: Create VM from Proxmox Template
  hosts: proxmox
  vars:
    ansible_python_interpreter: /opt/venv/bin/python
  tasks:
    - name: Clone Proxmox template
      community.general.proxmox_kvm:
        node: pve-in
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"
        api_host: 172.28.0.251
        api_port: 8006
        validate_certs: false
        storage: "local-lvm"
        full: true
        clone: "SRVCVDUBUNTU"
        name: "{{ vm_name }}"
        timeout: 300
        startup: yes
      register: clone_result

#    - name: Start VMs
#      proxmox_kvm:
#        api_host: 172.28.0.251
#        api_password: "{{ proxmox_pass }}"
#        api_user: "root@pam"
#        vmid: "{{ item.value.vmid }}"
#        node: pve-in
#        state: started
#      loop: "{{ lookup('dict', vms) }}"

#    - name: Wait for VM to be ready
#      retries: 10
#      delay: 15
#      until: clone_result is not failed

#    - name: Get VM details using Proxmox API
#      community.general.proxmox_kvm_info:
#        node: pve-in
#        api_user: "root@pam"
#        api_password: "{{ proxmox_pass }}"
#        api_host: 172.28.0.251
#        api_port: 8006
#        validate_certs: false
#      register: vm_info
#
#    - name: Extract IPv4 addresses
#      debug:
#        msg: >
#          VM IPv4 Addresses: {{
#            vm_info.instances | selectattr('name', 'equalto', vm_name) |
#            map(attribute='network') | list
#          }}
