---
- name: Create VM from Proxmox Template
  hosts: proxmox
  vars:
    ansible_python_interpreter: /opt/venv/bin/python
  tasks:
    - name: Clone Proxmox template
      community.general.proxmox_kvm:
        node: pve-in
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"
        api_host: 172.28.0.251
        api_port: 8006
        validate_certs: false
        storage: "local-lvm"
        full: true
        clone: "SRVCVDUBUNTU"
        name: "{{ vm_name }}"
        timeout: 300
        startup: yes
      register: clone_result

    - name: Start VM
      community.general.proxmox_kvm:
        node: pve-in
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"
        api_host: 172.28.0.251
        api_port: 8006
        validate_certs: false
        name: "{{ vm_name }}"
        state: started

    - name: Gather VM details using Proxmox API
      community.general.proxmox_kvm:
          node: pve-in
          api_user: "root@pam"
          api_password: "{{ proxmox_pass }}"
          api_host: 172.28.0.251
          api_port: 8006
          validate_certs: false
          name: "{{ vm_name }}"
      register: vm_info

    - name: Extract IP address from VM details
      debug:
        msg: >
          VM IPv4 Address: {{
            vm_info.instance.guest_agent['ip-addresses'] | 
            selectattr('ip-address-type', 'equalto', 'ipv4') | 
            map(attribute='ip-address') | join(', ')
          }}