172.28.0.251
172.28.1.200
172.28.0.132
[ubuntu_servers]
172.28.1.20 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_awx
172.28.1.23 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_awx