---
- name: Create VM from Proxmox Template (T-WIN-2022)
  hosts: proxmox
  vars:
    ansible_python_interpreter: /opt/venv/bin/python
  tasks:
    - name: Clone Proxmox template (T-WIN-2022)
      community.general.proxmox_kvm:
        node: pve-in
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"
        api_host: 172.28.0.251
        api_port: 8006
        validate_certs: false
        storage: "local-lvm"
        full: true
        clone: "T-WIN-2022"
        name: "{{ vm_name }}"
        timeout: 300
        startup: yes
      register: clone_result

    - name: Start VM
      community.general.proxmox_kvm:
        node: pve-in
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"
        api_host: 172.28.0.251
        api_port: 8006
        validate_certs: false
        name: "{{ vm_name }}"
        state: started

    - name: Wait for 30 seconds
      ansible.builtin.pause:
        seconds: 30
