- name: Install Docker and Docker Compose
  hosts: '{{ hostname }}'
  tasks:
    - name: Install yum-utils for repository management
      ansible.builtin.yum:
        name: yum-utils
        state: present

    - name: Add Docker Repository
      ansible.builtin.command:
        cmd: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker CE
      ansible.builtin.yum:
        name: docker-ce
        state: latest

    - name: Restart and enable docker
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true

    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.32.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker Compose installation
      ansible.builtin.command:
        cmd: docker-compose --version
