---
- name: Install Docker and utilities on Ubuntu
  hosts: "{{ hostname }}"
  become: true
  vars:
    docker_install: "false"  # Значение будет переопределено из Survey
    install_utilities: "false"  # Значение будет переопределено из Survey
  tasks:

    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install basic utilities
      ansible.builtin.apt:
        name:
          - net-tools
          - vim
          - wget
          - netcat
          - mlocate
          - mc
        state: present
      when: install_utilities == "true"

    - name: Install Docker dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
      when: docker_install == "true"

    - name: Add Docker’s official GPG key
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
        chmod a+r /etc/apt/keyrings/docker.asc
      when: docker_install == "true"

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: docker_install == "true"

    - name: Update package cache after adding Docker repo
      ansible.builtin.apt:
        update_cache: yes
      when: docker_install == "true"

    - name: Install Docker Engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      when: docker_install == "true"

    - name: Ensure Docker service is running and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      when: docker_install == "true"

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      when: docker_install == "true"

    - name: Verify Docker installation
      ansible.builtin.shell: docker --version
      register: docker_version_output
      changed_when: false
      when: docker_install == "true"

    - name: Show installed Docker version
      ansible.builtin.debug:
        msg: "Docker installed: {{ docker_version_output.stdout }}"
      when: docker_install == "true"
