---
- name: Create VM on Proxmox from ISO
  hosts: localhost
  gather_facts: false
  vars:
    proxmox_host: "172.28.0.251"
    proxmox_user: "root@pam"
    proxmox_password: "{{ proxmox_pass }}"
    proxmox_node: "pve-in"
    storage: "local-lvm"
    iso_image: "ubuntu-22.04.4-live-server-amd64.iso"
    vm_id: 110
    vm_name: "Ubuntu_VM_AWX"
    memory: 4096
    cores: 1
    disk_size: "32G"
    net_bridge: "vmbr1"

  tasks:
    - name: Create VM from ISO
      proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ vm_id }}"
        name: "{{ vm_name }}"
        memory: "{{ memory }}"
        cores: "{{ cores }}"
        net0: "virtio,bridge={{ net_bridge }}"
        ide2: "{{ storage }}:iso={{ iso_image }}"
        scsihw: virtio-scsi-pci
        scsi0: "{{ storage }}:{{ disk_size }}"
        bootdisk: scsi0
        ostype: l26
        boot: cdn
        state: present
        validate_certs: false

    - name: Start the VM
      proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        node: "{{ proxmox_node }}"
        vmid: "{{ vm_id }}"
        state: started
        validate_certs: false

    - name: Wait for VM to start
      pause:
        seconds: 30

    - name: Display VM creation details
      debug:
        msg: >
          Виртуальная машина "{{ vm_name }}" создана с ID {{ vm_id }}.
          Параметры:
          - Память: {{ memory }} MB
          - CPU: {{ cores }} ядро(а)
          - Диск: {{ disk_size }}
          - Сеть: {{ net_bridge }}
