---
- name: Create VM on Proxmox from ISO
  hosts: localhost
  gather_facts: false
  vars:
    proxmox_host: "172.28.0.251"
    proxmox_user: "root@pam"
    proxmox_password: "{{ proxmox_pass }}"  # Пароль передаётся через переменные окружения
    proxmox_node: "pve-in"
    storage: "local-lvm"
    iso_image: "ubuntu-22.04.4-live-server-amd64.iso"
    vm_id: 110  # Уникальный ID новой VM
    vm_name: "Ubuntu_VM_AWX"
    memory: 4096  # 4 ГБ
    cpus: 1  # 1 ядро
    disk_size: "32G"  # Размер диска
    net_bridge: "vmbr1"  # Сетевой мост

  tasks:
    - name: Create VM with SCSI disk and CD-ROM
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        validate_certs: false
        node: "{{ proxmox_node }}"
        vmid: "{{ vm_id }}"
        name: "{{ vm_name }}"
        memory: "{{ memory }}"
        cores: "{{ cpus }}"
        net:
          - model: "virtio"
            bridge: "{{ net_bridge }}"
        scsi:
          - storage: "{{ storage }}"
            size: "{{ disk_size }}"
        ide:
          - file: "{{ iso_image }}"
            media: "cdrom"
        ostype: "l26"  # Linux
        boot: "cdn"  # Порядок загрузки: CD-ROM -> Disk -> Network
        state: present
        timeout: 300

    - name: Start the VM
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        validate_certs: false
        node: "{{ proxmox_node }}"
        vmid: "{{ vm_id }}"
        state: started

    - name: Wait for VM to start
      pause:
        seconds: 60

    - name: Display VM creation status
      debug:
        msg: >
          Виртуальная машина "{{ vm_name }}" создана с ID {{ vm_id }} и запущена.
          Параметры:
          - Память: {{ memory }} MB
          - CPU: {{ cpus }} ядро(а)
          - Диск: {{ disk_size }}
          - Сеть: {{ net_bridge }}
