---
- name: Join Windows VM to Active Directory
  hosts: 172.28.1.23
  gather_facts: no
  tasks:

    - name: Ensure WinRM is enabled
      ansible.windows.win_service:
        name: WinRM
        state: started
        start_mode: auto

    - name: Join the Windows VM to the domain
      ansible.windows.win_domain_membership:
        dns_domain_name: "CVD"
        domain_admin_user: "a.bardashevich@cvd"
        domain_admin_password: "{{ domain_password }}"
        state: domain
      register: domain_join_result
      ignore_errors: yes

    - name: Reboot the machine if domain join required
      ansible.windows.win_reboot:
      when: domain_join_result.changed

    - name: Verify domain membership
      ansible.windows.win_shell: "whoami"
      register: whoami_output

    - name: Display logged-in user
      ansible.builtin.debug:
        msg: "Current user: {{ whoami_output.stdout }}"
